# Generated by Django 4.2.2 on 2023-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_alter_estoque_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='corredor',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='prateleira',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
