# Generated by Django 4.2.2 on 2023-06-28 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_alter_estoque_corredor_alter_estoque_prateleira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='corredor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='prateleira',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='setor',
            field=models.CharField(max_length=50),
        ),
    ]
