# Generated by Django 4.2.2 on 2023-06-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('quantidade', models.CharField(max_length=500)),
                ('descricao', models.CharField(max_length=500)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(max_length=500)),
                ('categoria', models.CharField(max_length=500)),
            ],
        ),
    ]
