# Generated by Django 4.2.2 on 2023-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compra', models.CharField(max_length=50, unique=True)),
                ('venda', models.CharField(max_length=50)),
                ('fiscal', models.CharField(max_length=50)),
                ('relatorioCompra', models.CharField(max_length=50)),
                ('relatorioVenda', models.CharField(max_length=50)),
            ],
        ),
    ]
