# Generated by Django 4.2.2 on 2023-06-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecursosH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=50)),
                ('salario', models.IntegerField()),
                ('cargaHoraria', models.IntegerField()),
                ('folhaPonto', models.CharField(max_length=50)),
                ('setor', models.CharField(max_length=50)),
            ],
        ),
    ]
